import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT

def draw_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#64748b")) # slate-500
    
    # Left aligned footer text
    canvas.drawString(54, 36, "Generated by ORYQ — oryq.ai")
    
    # Right aligned page number
    page_num = f"Page {doc.page}"
    canvas.drawRightString(doc.pagesize[0] - 54, 36, page_num)
    canvas.restoreState()

def escape_for_paragraph(text: str) -> str:
    if not text:
        return ""
    # Escape special characters that ReportLab XML parser expects to be entities
    escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Convert newlines to breaks
    return escaped.replace("\n", "<br/>")

def generate_scan_pdf(
    brand_name: str,
    website_url: str,
    score: float,
    total_prompts_run: int,
    brand_mentioned_count: int,
    results_summary: list[dict],
    competitor_data: dict | None,
    hallucinations: list[dict] | None,
    scan_date: str,
    missed_prompts: list[dict] | None = None,
    recommendations: list[dict] | None = None
) -> bytes:
    buffer = io.BytesIO()
    
    # Page setup: letter is 612 x 792 points. Margins 54pt (0.75 inch). Printable width is 504pt.
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Define custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#0f172a")
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#475569")
    )
    
    heading_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=8,
        spaceBefore=12
    )
    
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#334155")
    )
    
    body_bold = ParagraphStyle(
        'BodyTextBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    code_style = ParagraphStyle(
        'CodeText',
        parent=styles['Normal'],
        fontName='Courier',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#38bdf8") # light blue color for high contrast inside dark box
    )
    
    story = []
    
    # Horizontal line separator using a thin Table
    line_table = Table([['']], colWidths=[504])
    line_table.setStyle(TableStyle([
        ('LINEABOVE', (0,0), (-1,-1), 1, colors.HexColor("#cbd5e1")),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    
    def append_page_header(story_list):
        logo_html = '<b><font color="#2563eb" size="18">ORYQ</font></b> <font size="14" color="#0f172a"><b>&mdash; AI Visibility Report</b></font>'
        story_list.append(Paragraph(logo_html, title_style))
        story_list.append(Spacer(1, 4))
        sub_text = f"<b>Brand:</b> {escape_for_paragraph(brand_name)} &nbsp;&nbsp;|&nbsp;&nbsp; <b>Website:</b> {escape_for_paragraph(website_url)} &nbsp;&nbsp;|&nbsp;&nbsp; <b>Scan Date:</b> {escape_for_paragraph(scan_date)}"
        story_list.append(Paragraph(sub_text, subtitle_style))
        story_list.append(Spacer(1, 6))
        story_list.append(line_table)
        story_list.append(Spacer(1, 15))
        
    def make_bordered_box(label: str, content: str, content_style: ParagraphStyle, border_hex: str, bg_hex: str) -> Table:
        escaped_content = escape_for_paragraph(content)
        p_text = f"<b>{label}</b><br/>{escaped_content}"
        p = Paragraph(p_text, content_style)
        t = Table([[p]], colWidths=[504])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor(bg_hex)),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor(border_hex)),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 10),
            ('RIGHTPADDING', (0,0), (-1,-1), 10),
        ]))
        return t

    # --- PAGE 1: SCORE SUMMARY & COMPETITORS ---
    append_page_header(story)
    
    story.append(Paragraph("Visibility Audit Summary", heading_style))
    story.append(Spacer(1, 6))
    
    # Colored box logic for score
    if score >= 70:
        box_bg = colors.HexColor("#dcfce7")       # green-100
        text_color = colors.HexColor("#16a34a")   # green-600
        border_color = colors.HexColor("#bbf7d0") # green-200
    elif score >= 40:
        box_bg = colors.HexColor("#fef3c7")       # amber-100
        text_color = colors.HexColor("#d97706")   # amber-600
        border_color = colors.HexColor("#fde68a") # amber-200
    else:
        box_bg = colors.HexColor("#fee2e2")       # red-100
        text_color = colors.HexColor("#dc2626")   # red-600
        border_color = colors.HexColor("#fca5a5") # red-200
        
    score_str = f"{int(score)}" if isinstance(score, (int, float)) and score.is_integer() else f"{score:.1f}"
    
    score_p_style = ParagraphStyle(
        'ScoreP',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        alignment=TA_CENTER,
        textColor=text_color
    )
    score_lbl_style = ParagraphStyle(
        'ScoreLbl',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        alignment=TA_CENTER,
        textColor=text_color
    )
    
    score_p = Paragraph(f"{score_str}/100", score_p_style)
    score_lbl = Paragraph("VISIBILITY SCORE", score_lbl_style)
    
    score_box_table = Table([[score_p], [score_lbl]], colWidths=[110])
    score_box_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), box_bg),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,0), 10),
        ('BOTTOMPADDING', (0,0), (-1,0), 2),
        ('TOPPADDING', (0,1), (-1,1), 2),
        ('BOTTOMPADDING', (0,1), (-1,1), 10),
        ('BOX', (0,0), (-1,-1), 1.5, border_color),
    ]))
    
    # Right column flowables: Description & Provider breakdown
    escaped_brand_name = escape_for_paragraph(brand_name)
    mention_text = f"<b>{brand_mentioned_count} out of {total_prompts_run}</b> AI responses mentioned <b>{escaped_brand_name}</b>."
    mention_p = Paragraph(mention_text, body_style)
    
    prov_table_data = [["Provider", "Score", "Mentions / Total"]]
    for item in results_summary:
        p_name = item.get("provider", "N/A").capitalize()
        p_score = item.get("score", 0.0)
        p_score_str = f"{int(p_score)}" if isinstance(p_score, (int, float)) and p_score.is_integer() else f"{p_score:.1f}"
        p_mentions = item.get("mentions", 0)
        p_total = item.get("total", 0)
        prov_table_data.append([p_name, f"{p_score_str}/100", f"{p_mentions} / {p_total}"])
        
    prov_table = Table(prov_table_data, colWidths=[120, 100, 130])
    prov_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#151b2e")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ('TOPPADDING', (0,0), (-1,-1), 3),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,1), (-1,-1), 8),
    ]))
    
    right_column_flowables = [
        mention_p,
        Spacer(1, 6),
        prov_table
    ]
    
    # Combine score box and right column side-by-side
    summary_layout = Table([[score_box_table, right_column_flowables]], colWidths=[130, 374])
    summary_layout.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 0),
        ('RIGHTPADDING', (0,0), (-1,-1), 0),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    
    story.append(summary_layout)
    story.append(Spacer(1, 15))
    
    # Competitor Comparison (if present)
    if competitor_data:
        story.append(Paragraph("Competitive Position", heading_style))
        
        rank = competitor_data.get("rank", 1)
        comps = competitor_data.get("competitors", [])
        total_brands = 1 + len(comps)
        
        rank_text = f"<b>Rank #{rank}</b> out of <b>{total_brands}</b> brands scanned in this industry."
        story.append(Paragraph(rank_text, body_style))
        story.append(Spacer(1, 6))
        
        main_b = competitor_data.get("main_brand", {})
        main_name = main_b.get("name", brand_name)
        main_score = main_b.get("score", score)
        
        brand_entries = [(main_name, main_score, True)]
        for comp in comps:
            brand_entries.append((comp.get("name", "Unknown"), comp.get("score", 0.0), False))
            
        brand_entries.sort(key=lambda x: x[1], reverse=True)
        
        comp_table_data = [["Brand Name", "Visibility Score"]]
        main_row_idx = -1
        for idx, (b_name, b_score, is_main) in enumerate(brand_entries, start=1):
            b_score_str = f"{int(b_score)}" if isinstance(b_score, (int, float)) and b_score.is_integer() else f"{b_score:.1f}"
            comp_table_data.append([escape_for_paragraph(b_name), f"{b_score_str}/100"])
            if is_main:
                main_row_idx = idx
                
        comp_table = Table(comp_table_data, colWidths=[250, 254])
        comp_table_style = [
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#151b2e")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
            ('TOPPADDING', (0,0), (-1,-1), 3),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
            ('RIGHTPADDING', (0,0), (-1,-1), 6),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
            ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,1), (-1,-1), 8),
        ]
        
        if main_row_idx != -1:
            comp_table_style.append(('BACKGROUND', (0, main_row_idx), (-1, main_row_idx), colors.HexColor("#e0f2fe")))
            comp_table_style.append(('FONTNAME', (0, main_row_idx), (-1, main_row_idx), 'Helvetica-Bold'))
            
        comp_table.setStyle(TableStyle(comp_table_style))
        story.append(comp_table)
        story.append(Spacer(1, 10))

    # --- PAGE 2: MISSED OPPORTUNITIES ---
    story.append(PageBreak())
    append_page_header(story)
    
    story.append(Paragraph("Missed Opportunities — AI Responses Without [Brand]", heading_style))
    story.append(Spacer(1, 4))
    
    if not missed_prompts or len(missed_prompts) == 0:
        success_p = Paragraph(f'<b><font color="#16a34a">Your brand was mentioned in 100% of tested AI queries.</font></b>', body_style)
        story.append(success_p)
    else:
        missed_count = total_prompts_run - brand_mentioned_count
        subtext_str = f"<b>{missed_count} out of {total_prompts_run}</b> AI queries did not mention your brand. Here's exactly what AI said instead:"
        story.append(Paragraph(subtext_str, body_style))
        story.append(Spacer(1, 10))
        
        items_shown = missed_prompts[:5]
        for idx, item in enumerate(items_shown):
            # Prompt block
            p_box = make_bordered_box("PROMPT:", item.get("prompt_text", ""), body_style, "#cbd5e1", "#f8fafc")
            story.append(p_box)
            story.append(Spacer(1, 4))
            
            # Response block (red-tinted)
            resp_raw = item.get("response_snippet", "") or item.get("response_text", "") or ""
            # Truncate response to ~250 characters
            if len(resp_raw) > 250:
                resp_raw = resp_raw[:250] + "..."
            
            r_box = make_bordered_box("AI RESPONSE:", resp_raw, body_style, "#fca5a5", "#fef2f2")
            story.append(r_box)
            story.append(Spacer(1, 2))
            
            # Provider tag
            prov_text = f'<font color="#64748b" size="8"><b>AI Provider:</b> {item.get("provider", "Unknown").capitalize()}</font>'
            story.append(Paragraph(prov_text, body_style))
            story.append(Spacer(1, 10))
            
        if missed_count > 5:
            remaining = missed_count - 5
            more_html = f'<font color="#64748b" size="8"><i>* + {remaining} more missed opportunities found &mdash; view full report in your dashboard.</i></font>'
            story.append(Paragraph(more_html, body_style))

    # --- PAGE 3: DETECTED FACTUAL ERRORS ---
    story.append(PageBreak())
    append_page_header(story)
    
    story.append(Paragraph("Detected Factual Errors", heading_style))
    story.append(Spacer(1, 4))
    
    if not hallucinations or len(hallucinations) == 0:
        success_html = '<b><font color="#16a34a">No factual errors detected</font></b>'
        story.append(Paragraph(success_html, body_style))
    else:
        items_to_show = hallucinations[:5]
        for idx, h in enumerate(items_to_show):
            claim = h.get("claim", "")
            provider = h.get("provider", "Unknown").capitalize()
            severity = h.get("severity", "medium")
            source_resp = h.get("source_response", "") or ""
            
            if len(source_resp) > 300:
                source_resp = source_resp[:300] + "..."
                
            # Bold claim
            story.append(Paragraph(f"<b>Claim Checked:</b> {escape_for_paragraph(claim)}", body_bold))
            story.append(Spacer(1, 4))
            
            # Proof box (red-tinted background)
            proof_box = make_bordered_box("PROOF (AI Response):", source_resp, body_style, "#fca5a5", "#fef2f2")
            story.append(proof_box)
            story.append(Spacer(1, 2))
            
            # Metadata
            detail_html = f'<font color="#64748b" size="8"><b>Provider:</b> {provider} &nbsp;|&nbsp; <b>Severity:</b> {severity.upper()}</font>'
            story.append(Paragraph(detail_html, body_style))
            story.append(Spacer(1, 10))
            
        if len(hallucinations) > 5:
            remaining = len(hallucinations) - 5
            more_html = f'<font color="#64748b" size="8"><i>* + {remaining} more factual errors found &mdash; view full report in your dashboard.</i></font>'
            story.append(Paragraph(more_html, body_style))

    # --- PAGE 4: RECOMMENDED FIXES ---
    story.append(PageBreak())
    append_page_header(story)
    
    story.append(Paragraph("Recommended Fixes — Ready to Use", heading_style))
    story.append(Spacer(1, 4))
    
    if not recommendations or len(recommendations) == 0:
        info_html = '<b><font color="#475569">No critical fixes needed at this time.</font></b>'
        story.append(Paragraph(info_html, body_style))
    else:
        for idx, rec in enumerate(recommendations):
            # Recommendation Header
            category_label = rec.get("category", "").replace("_", " ").upper()
            impact = rec.get("impact", "Medium")
            effort = rec.get("effort", "Medium")
            is_high_impact = "high" in impact.lower()
            
            badge_color = "#2563eb" if is_high_impact else "#16a34a"
            
            title_text = f"<b>{escape_for_paragraph(rec.get('title', ''))}</b>"
            story.append(Paragraph(title_text, body_bold))
            
            meta_text = f'<font color="#64748b" size="8"><b>Category:</b> {category_label} &nbsp;|&nbsp; <b>Effort:</b> {effort} &nbsp;|&nbsp; <b>Impact:</b> <font color="{badge_color}"><b>{impact}</b></font></font>'
            story.append(Paragraph(meta_text, body_style))
            story.append(Spacer(1, 2))
            
            action_text = f"<i>Advice: \"{escape_for_paragraph(rec.get('action', ''))}\"</i>"
            story.append(Paragraph(action_text, body_style))
            story.append(Spacer(1, 4))
            
            # Check for generated content
            gen_content = rec.get("generated_content")
            if gen_content and isinstance(gen_content, dict):
                g_text = gen_content.get("generated_text", "")
                g_code = gen_content.get("generated_code", "")
                g_type = gen_content.get("content_type", "Suggested Copy")
                inst = gen_content.get("instructions", "")
                
                # Show suggested copy (light blue box)
                if g_text:
                    text_box = make_bordered_box(f"{g_type.upper()} — READY TO USE:", g_text, body_style, "#bae6fd", "#f0f9ff")
                    story.append(text_box)
                    story.append(Spacer(1, 4))
                    
                # Show suggested code (dark monospace box)
                if g_code:
                    code_box = make_bordered_box("SUGGESTED CODE:", g_code, code_style, "#334155", "#0f172a")
                    story.append(code_box)
                    story.append(Spacer(1, 4))
                    
                # Instructions
                if inst:
                    inst_html = f'<font color="#475569" size="8"><b>Deployment Instructions:</b> <i>{escape_for_paragraph(inst)}</i></font>'
                    story.append(Paragraph(inst_html, body_style))
                    
            story.append(Spacer(1, 10))
            
    # Build document
    doc.build(story, onFirstPage=draw_footer, onLaterPages=draw_footer)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
