import json
import logging
from typing import Dict, Any, List, Optional

from app.scanner.providers.groq_provider import call_groq
from app.scanner.providers.openai_provider import call_openai
from app.config import settings

logger = logging.getLogger(__name__)

async def verify_claim_with_openai(brand_name: str, claim: str, original_text: str) -> str:
    """
    Secondary verification for high and critical severity claims using OpenAI (GPT-4o mini).
    Returns verified severity ('low', 'medium', 'high', 'critical').
    """
    if not settings.OPENAI_API_KEY:
        logger.warning("OPENAI_API_KEY not configured. Skipping OpenAI claim verification.")
        return "high"

    prompt = f"""You are a hallucination verification agent for B2B brands.
Brand Name: '{brand_name}'
Claim made in AI response: \"{claim}\"
Full Context: \"\"\"{original_text}\"\"\"

Evaluate if this claim is a factual error, severe inaccuracy, or false statement regarding {brand_name}.
Rate final severity strictly as: 'low', 'medium', 'high', or 'critical'.

Respond strictly with valid JSON:
{{
  "verified_severity": "low" | "medium" | "high" | "critical",
  "reasoning": "short explanation"
}}
"""
    try:
        response_text, cost_usd, latency_ms = await call_openai(prompt)
        clean_json = response_text.strip()
        if "```json" in clean_json:
            clean_json = clean_json.split("```json")[1].split("```")[0].strip()
        elif "```" in clean_json:
            clean_json = clean_json.split("```")[1].split("```")[0].strip()

        data = json.loads(clean_json)
        verified_sev = str(data.get("verified_severity", "high")).lower()
        if verified_sev in ["low", "medium", "high", "critical"]:
            return verified_sev
        return "high"
    except Exception as e:
        logger.error(f"Error during OpenAI claim verification: {e}")
        return "high"

async def detect_hallucinations(
    text: str,
    brand_name: str,
    provider: str
) -> Dict[str, Any]:
    """
    Enhanced hallucination detector using Groq + OpenAI GPT-4o verification for high severity.
    Returns: {
        "has_hallucination": bool,
        "hallucination_text": str | None,
        "severity": str | None,
        "status": "unreviewed"
    }
    """
    if not text or len(text.strip()) < 20:
        return {
            "has_hallucination": False,
            "hallucination_text": None,
            "severity": "low",
            "status": "unreviewed"
        }

    prompt = f"""You are a factual accuracy auditor. Analyze the following text generated by an AI model regarding brand '{brand_name}'.
Identify any unverified, incorrect, or fabricated factual claims made about '{brand_name}' (e.g. false features, incorrect pricing, non-existent outages, fake executive names, false acquisition claims).

Text:
\"\"\"
{text}
\"\"\"

If hallucinations exist, extract the specific claim and rate severity as 'low', 'medium', 'high', or 'critical'.
If no hallucinations exist, set has_hallucination to false.

Respond STRICTLY with valid JSON:
{{
  "has_hallucination": bool,
  "claim": "extracted hallucination text or empty string",
  "severity": "low" | "medium" | "high" | "critical"
}}
"""

    try:
        response_text, cost_usd, latency_ms = await call_groq(prompt, temperature=0.0, max_tokens=300)
        clean_json = response_text.strip()
        if "```json" in clean_json:
            clean_json = clean_json.split("```json")[1].split("```")[0].strip()
        elif "```" in clean_json:
            clean_json = clean_json.split("```")[1].split("```")[0].strip()

        data = json.loads(clean_json)
        has_hallucination = bool(data.get("has_hallucination", False))
        claim = str(data.get("claim", "")).strip()
        severity = str(data.get("severity", "low")).lower()

        if not has_hallucination or not claim:
            return {
                "has_hallucination": False,
                "hallucination_text": None,
                "severity": "low",
                "status": "unreviewed"
            }

        # Secondary verification with OpenAI GPT-4o for high or critical severity
        if severity in ["high", "critical"]:
            severity = await verify_claim_with_openai(brand_name, claim, text)

        return {
            "has_hallucination": True,
            "hallucination_text": claim,
            "severity": severity,
            "status": "unreviewed"
        }
    except Exception as e:
        logger.error(f"Error in detect_hallucinations: {e}")
        return {
            "has_hallucination": False,
            "hallucination_text": None,
            "severity": "low",
            "status": "unreviewed"
        }
